{% set name = "kleborate" %}
{% set version = "3.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kleborate-{{ version }}.tar.gz"
  sha256: 8dc3c88fcee916c22de57fca4d16b9c6336af94fe7322123d05b30149197dd53

build:
  number: 0
  noarch: python
  entry_points:
    -  kleborate = kleborate.__main__:main
  script:
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage('kleborate', max_pin='x') }}


requirements:
  host:
    - pip
    - python >=3.9
    - numpy >=1.22
  run:
    - python >=3.9
    - biopython >=1.83
    - numpy >=1.22
    - dna_features_viewer
    - minimap2
    - mash
    - kaptive

test:
  imports:
    - kleborate
  commands:
    - kaptive --help
    - minimap2 --help
    - kleborate --help

about:
  home: "https://kleboratemodular.readthedocs.io/"
  dev_url: "https://github.com/klebgenomics/KleborateModular"
  summary: "Kleborate: a tool for typing and screening pathogen genome assemblies"
  license: "GNU General Public License v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE
  doc_url: "https://kleboratemodular.readthedocs.io/"


extra:
  recipe-maintainers:
    - Mary Maranga
